In [1]:
from sklearn.model_selection import cross_validate, LeaveOneGroupOut
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import networkx as nx


In [2]:
df = pd.read_csv('descriptors.csv')

In [3]:
# Populate the graph with edges and attributes
graphs = {}
for _, row in df.iterrows():
    # Check if graph_id exists, if not create a new DiGraph
    if row['graph_id'] not in graphs:
        graphs[row['graph_id']] = nx.DiGraph()
    G = graphs[row['graph_id']]
    
    # Add an edge if is_causal is True
    if row['is_causal']: 
        G.add_edge(row['edge_source'], row['edge_dest'])
    else:
        G.add_node(row['edge_source'])
        G.add_node(row['edge_dest'])


In [4]:
from graphviz import Digraph

for key, graph in graphs.items():
    G_dot = Digraph(engine="dot",format='png')

    for node in graph.nodes():
        G_dot.node(str(node))
    for edge in graph.edges():
        G_dot.edge(str(edge[0]), str(edge[1]))

    # Render the graph in a hierarchical layout
    G_dot.render(f"pics/graph_{key}.png", view=False)

In [1]:
#load dags.pkl
import pickle
with open('dags.pkl', 'rb') as f:
    dags = pickle.load(f)

    

In [2]:
from graphviz import Digraph

for key, graph in enumerate(dags):
    G_dot = Digraph(engine="dot",format='png')

    for node in graph.nodes():
        G_dot.node(str(node))
    for edge in graph.edges():
        G_dot.edge(str(edge[0]), str(edge[1]))

    # Render the graph in a hierarchical layout
    G_dot.render(f"pics/{key}_graph.png", view=False)

# Checking the Observations

# Reconstructing the formula

In [4]:
[(i, j) for i in range(3) for j in range(3)]

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [3]:
import numpy as np
np.round(np.random.uniform(low=-1, high=1),2)

0.35

In [2]:
import pickle

In [3]:
#load observations.pkl
with open('observations.pkl', 'rb') as f:
    observations = pickle.load(f)
    

In [4]:
import sys
sys.path.append("../d2c")
from utils import dag_to_formula

In [5]:
#load updated_dags.pkl
with open('updated_dags.pkl', 'rb') as f:
    updated_dags = pickle.load(f)

In [6]:
dag = updated_dags[-1]


formula = dag_to_formula(dag)
print(formula)


6 = -0.72582*6_t-1 + 0.29921*6_t-2 + 0.52695*6_t-3 + 0
5 = -0.70094*6_t-1 + -0.70094*6_t-2 + -0.70094*6_t-3 + 0.63289*5_t-1 + 0.48095*5_t-2 + 0.13308*5_t-3 + 0
4 = -0.92196*6_t-1 + -0.92196*6_t-2 + -0.92196*6_t-3 + -0.07633*5_t-1 + -0.07633*5_t-2 + -0.07633*5_t-3 + 0.41895*4_t-1 + -0.86149*4_t-2 + -0.32403*4_t-3 + 0
3 = 0.2103*6_t-1 + 0.2103*6_t-2 + 0.2103*6_t-3 + -0.32496*5_t-1 + -0.32496*5_t-2 + -0.32496*5_t-3 + -0.21081*4_t-1 + -0.21081*4_t-2 + -0.21081*4_t-3 + 0.83639*3_t-1 + -0.50588*3_t-2 + 0.0065*3_t-3 + 0
2 = 0.31272*6_t-1 + 0.31272*6_t-2 + 0.31272*6_t-3 + -0.79835*5_t-1 + -0.79835*5_t-2 + -0.79835*5_t-3 + -0.4269*4_t-1 + -0.4269*4_t-2 + -0.4269*4_t-3 + 0.07774*3_t-1 + 0.07774*3_t-2 + 0.07774*3_t-3 + 0.93778*2_t-1 + 0.31913*2_t-2 + -0.37868*2_t-3 + 0
1 = 0.03728*6_t-1 + 0.03728*6_t-2 + 0.03728*6_t-3 + -0.07979*5_t-1 + -0.07979*5_t-2 + -0.07979*5_t-3 + 0.49971*4_t-1 + 0.49971*4_t-2 + 0.49971*4_t-3 + -0.08325*3_t-1 + -0.08325*3_t-2 + -0.08325*3_t-3 + 0.14033*2_t-1 + 0.14033*2_t-2

In [7]:
observations[-1]

0             1             2             3             4  \
0   -6.770900e-01 -7.795700e-01 -5.163600e-01 -3.297900e-01  9.307500e-01   
1    9.410000e-01 -1.011500e-01  1.383300e-01 -3.250900e-01 -8.852000e-01   
2   -3.330500e-01 -2.580400e-01 -5.635500e-01  4.033600e-01  8.582100e-01   
3   -2.833050e+00 -4.421700e-01 -1.919550e+00 -1.160400e-01  2.819500e-01   
4   -3.505870e+00 -3.061000e-01 -3.415640e+00 -8.550700e-01 -8.050000e-02   
..            ...           ...           ...           ...           ...   
147 -9.073990e+09 -3.167585e+09 -3.464725e+09 -3.711944e+08 -4.095479e+07   
148 -1.044532e+10 -3.646296e+09 -3.988343e+09 -4.272923e+08 -4.714436e+07   
149 -1.202391e+10 -4.197354e+09 -4.591093e+09 -4.918683e+08 -5.426944e+07   
150 -1.384105e+10 -4.831691e+09 -5.284936e+09 -5.662034e+08 -6.247109e+07   
151 -1.593283e+10 -5.561896e+09 -6.083638e+09 -6.517725e+08 -7.191197e+07   

                5        6  
0    8.244300e-01  0.00263  
1   -6.754000e-02 -0.52714  
2    9.912600e-01  0.97408  
3    3.781400e-01 -0.86706  
4    1.047580e+00  0.64771  
..            ...      ...  
147  3.528297e+08 -0.00936  
148  4.061521e+08  0.00905  
149  4.675331e+08 -0.00469  
150  5.381905e+08  0.00392  
151  6.195261e+08  0.01382  

[152 rows x 7 columns]

In [15]:
for i in range(10):
    print(observations[i])

           0          1        2
0   -0.99844    0.98442  0.23496
1    0.22331   -0.98587 -0.95388
2    0.04955   -0.20028 -0.90667
3   -0.04738    0.22680  1.11966
4    0.01777   -1.37269  0.03034
..       ...        ...      ...
297  0.02254  -77.75814  0.03542
298  0.03577  124.85397  0.04834
299  0.00735 -136.93057  0.00017
300  0.04248  108.63246  0.02837
301  0.07918  -47.75059  0.06796

[302 rows x 3 columns]
           0        1        2
0    0.22426  0.18966 -0.49878
1    0.14986  0.04463  0.35355
2   -0.36073 -0.06368 -0.36801
3    0.58093 -0.13256  0.25970
4   -0.71243 -0.17278 -0.29328
..       ...      ...      ...
295 -0.02055 -0.21930 -0.05235
296  0.03794 -0.22651 -0.02127
297 -0.02542 -0.22325 -0.05980
298  0.07010 -0.20111 -0.02780
299 -0.03134 -0.19849 -0.05313

[300 rows x 3 columns]
           0        1        2
0   -0.43488  0.83368 -0.58376
1    0.17557  0.56312  0.31458
2   -0.07940 -0.11166 -0.13506
3    0.01852 -0.06045  0.08543
4   -0.01752 -0.16200 -0.0118

In [88]:
import numpy as np
np.random.rand(7, 7)*2 -1 

array([[-0.4116396 ,  0.59918992, -0.05521327, -0.96344891, -0.28722392,
         0.41178005, -0.46637332],
       [-0.36274806, -0.94912366,  0.70995491, -0.34068037, -0.55014107,
         0.73657334, -0.39524943],
       [ 0.27294033, -0.52211236, -0.0163236 ,  0.14364735, -0.09822959,
         0.61521106,  0.60795329],
       [-0.73870347, -0.73798428, -0.84602041,  0.67001708,  0.04804186,
        -0.16917231,  0.89916076],
       [ 0.92477042,  0.64188493, -0.99546754, -0.45671148, -0.28165316,
         0.71274447, -0.58608868],
       [-0.00413877, -0.65492847,  0.5151952 ,  0.22311102, -0.85539062,
         0.86236875,  0.26217668],
       [ 0.31001345,  0.73421258,  0.43562432,  0.59459153, -0.36976323,
         0.09532587, -0.83274745]])

In [24]:
from statsmodels.tsa.api import VAR
import numpy as np
#np from txt
data = np.loadtxt('../causeme/experiments/linear-VAR_N-3_T-150_0198.txt')
# Fit the VAR model
model = VAR(data)
results = model.fit(maxlags=5, ic='aic')
print(results.params)


[[ 0.20921354  0.19466644  0.03685556]
 [ 0.80976437 -0.02165628  0.07613718]
 [ 0.1304932   0.95714291  0.04572878]
 [-0.06123438  0.02061111  0.39562886]
 [ 0.07480246  0.14377912  0.11043204]
 [-0.08990433 -0.13905322 -0.00875466]
 [ 0.19277196 -0.03335154 -0.07197485]]
